### ISSUE TITLE
ability to overwrite how a type is going to be generated in the spec

### ISSUE THREAD

**Issue by phenpessoa** [go-fuego/fuego#222]
**Is your feature request related to a problem? Please describe.**
Yes, currently there is no way to change how a type is going to be described in the OpenAPI spec, even though we might be using custom Marshalers/Unmarshalers.

**Describe the solution you'd like**
I'd like to have an option to manually overwrite how a type will be described in the OpenAPI spec. I was thinking that maybe it could be an interface that the type implements and returns some sort of data of how it should be described. But open to suggestions.

**Describe alternatives you've considered**
Currently the only alternative is editing the spec file manually.

**Additional context**
To give a concrete example, I have this type:
```go
type Foo struct {
    Bar Option[string] `json:"bar"`
}

type Option[T any] struct {
    Valid bool
    Val   T
}
```
And in the spec it will show up as
```yml
Foo:
  description: Foo schema
  properties:
    bar:
      properties:
        Val:
          type: string
        Valid:
          type: boolean
      type: object
  type: object
```
But, the option field there basically is just a way to make the field nullable, so I'd like it to be encoded as:
```yml
Foo:
  description: Foo schema
  properties:
    bar:
      type: [string, 'null']
  type: object
```
