### ISSUE TITLE
Simpler authentication schemas

### ISSUE THREAD

**Issue by DimShadoWWW** [go-fuego/fuego#243]
I'm trying to use fuego to create an API that uses a header 'X-API-KEY' as access control with a funtion that validate its value and give or refuses access to a group of endpoints:

```
  securitySchemes:
    ApiKeyAuth:
      description: api key autentication
      in: header
      name: X-API-KEY
      type: apiKey
```

I could not find how to define it in fuego. Fuego can only use JWT autentication?
